---
redir-port: 7892
tproxy-port: 7895
port: 7890
socks-port: 7891
mixed-port: 7893
mode: rule
allow-lan: true
external-controller: 0.0.0.0:9090
secret: ''
bind-address: "*"
external-ui: "/usr/share/openclash/ui"
external-ui-name: metacubexd
keep-alive-interval: 15
keep-alive-idle: 600
ipv6: false
external-controller-cors:
  allow-origins:
  - " 10.168.10.250"
  allow-private-network: true
geox-url: {}
authentication:
- Clash:puCtjqRY
PProviders:
  type: http
  interval: 86400
  health-check: &1
    enable: true
    url: https://cp.cloudflare.com
    interval: 300
    timeout: 1000
    tolerance: 100
  filter: "^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
UrlTest:
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
FallBack:
  type: fallback
  interval: 60
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
FilterHK: "^(?=.*(?i)(港|\U0001F1ED\U0001F1F0|HK|Hong|HKG))(?!.*(排除1|排除2|5x)).*$"
FilterSG: "^(?=.*(?i)(坡|\U0001F1F8\U0001F1EC|SG|Sing|SIN|XSP))(?!.*(排除1|排除2|5x)).*$"
FilterJP: "^(?=.*(?i)(日|\U0001F1EF\U0001F1F5|JP|Japan|NRT|HND|KIX|CTS|FUK))(?!.*(排除1|排除2|5x)).*$"
FilterKR: "^(?=.*(?i)(韩|\U0001F1F0\U0001F1F7|韓|首尔|南朝鲜|KR|KOR|Korea|South))(?!.*(排除1|排除2|5x)).*$"
FilterUS: "^(?=.*(?i)(美|\U0001F1FA\U0001F1F8|US|USA|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD))(?!.*(排除1|排除2|5x)).*$"
FilterTW: "^(?=.*(?i)(台|\U0001F1FC\U0001F1F8|\U0001F1F9\U0001F1FC|TW|tai|TPE|TSA|KHH))(?!.*(排除1|排除2|5x)).*$"
FilterEU: "^(?=.*(?i)(奥|比|保|克罗地亚|塞|捷|丹|爱沙|芬|法|德|希|匈|爱尔|意|拉|立|卢|马其它|荷|波|葡|罗|斯洛伐|斯洛文|西|瑞|英|\U0001F1E7\U0001F1EA|\U0001F1E8\U0001F1FF|\U0001F1E9\U0001F1F0|\U0001F1EB\U0001F1EE|\U0001F1EB\U0001F1F7|\U0001F1E9\U0001F1EA|\U0001F1EE\U0001F1EA|\U0001F1EE\U0001F1F9|\U0001F1F1\U0001F1F9|\U0001F1F1\U0001F1FA|\U0001F1F3\U0001F1F1|\U0001F1F5\U0001F1F1|\U0001F1F8\U0001F1EA|\U0001F1EC\U0001F1E7|CDG|FRA|AMS|MAD|BCN|FCO|MUC|BRU))(?!.*(排除1|排除2|5x)).*$"
FilterOther: "^(?!.*(DIRECT|美|港|坡|台|新|日|韩|奥|比|保|克罗地亚|塞|捷|丹|爱沙|芬|法|德|希|匈|爱尔|意|拉|立|卢|马其它|荷|波|葡|罗|斯洛伐|斯洛文|西|瑞|英|\U0001F1ED\U0001F1F0|\U0001F1FC\U0001F1F8|\U0001F1F9\U0001F1FC|\U0001F1F8\U0001F1EC|\U0001F1EF\U0001F1F5|\U0001F1F0\U0001F1F7|\U0001F1FA\U0001F1F8|\U0001F1EC\U0001F1E7|\U0001F1E6\U0001F1F9|\U0001F1E7\U0001F1EA|\U0001F1E8\U0001F1FF|\U0001F1E9\U0001F1F0|\U0001F1EB\U0001F1EE|\U0001F1EB\U0001F1F7|\U0001F1E9\U0001F1EA|\U0001F1EE\U0001F1EA|\U0001F1EE\U0001F1F9|\U0001F1F1\U0001F1F9|\U0001F1F1\U0001F1FA|\U0001F1F3\U0001F1F1|\U0001F1F5\U0001F1F1|\U0001F1F8\U0001F1EA|HK|TW|SG|JP|KR|US|GB|CDG|FRA|AMS|MAD|BCN|FCO|MUC|BRU|HKG|TPE|TSA|KHH|SIN|XSP|NRT|HND|KIX|CTS|FUK|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD|LHR|LGW))"
FilterAll: "^(?!.*(DIRECT|群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
SelectFB:
  type: select
  proxies: &2
  - 故障转移
  - 香港自动
  - 台湾自动
  - 新加坡自动
  - 日本自动
  - 韩国自动
  - 美国自动
SelectUS:
  type: select
  proxies: &3
  - 美国自动
  - 台湾自动
  - 新加坡自动
  - 日本自动
  - 韩国自动
SelectOne:
  type: select
  proxies: &4
  - 一键连
  - 故障转移
  - 香港自动
  - 台湾自动
  - 新加坡自动
  - 日本自动
  - 韩国自动
  - 美国自动
proxy-providers:
  iKuuu_V2:
    type: http
    interval: 86400
    health-check: *1
    filter: "^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
    url: https://r82dq.no-mad-world.club/link/chnedscIWPZwCyUT?clash=3&extend=1
    override:
      additional-prefix: "[iKuuu_V2] "
    path: "./proxy_provider/sub1"
  宝可梦1398:
    type: http
    interval: 86400
    health-check: *1
    filter: "^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
    url: https://52pokemon.xz61.cn/api/v1/client/subscribe?token=9c1156871b9b5f2593242e03c9bea859
    override:
      additional-prefix: "[宝可梦1398] "
    path: "./proxy_provider/sub2"
  容器☁:
    type: http
    interval: 86400
    health-check: *1
    filter: "^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
    url: https://docker.anycast.cloudns.org/api/v1/client/subscribe?token=6bda3543dba763bc5fd7efc2fccd5017
    override:
      additional-prefix: "[容器☁] "
    path: "./proxy_provider/sub3"
  sub4:
    type: http
    interval: 86400
    health-check: *1
    filter: "^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
    url: https://gist.githubusercontent.com/byrisk/b8954fed7476b150ccb71e41e9ed1f1e/raw/MQFree.yaml
    override:
      additional-prefix: "[Other] "
    path: "./proxy_provider/sub4"
  星链Starlink:
    type: http
    interval: 86400
    health-check: *1
    filter: "^(?!.*(群|邀请|返利|循环|官网|客服|网站|网址|获取|订阅|流量|到期|机场|下次|版本|官址|备用|过期|已用|联系|邮箱|工单|贩卖|通知|倒卖|防止|国内|地址|频道|无法|说明|使用|提示|特别|访问|支持|教程|关注|更新|作者|加入|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author))"
    url: https://xship.top/v1/subscribe?starlink=iTsJ64W5zPT3_VwTUasugvu3
    override:
      additional-prefix: "[星链Starlink] "
    path: "./proxy_provider/sub5"
profile:
  store-selected: true
  store-fake-ip: true
sniffer:
  enable: true
  override-destination: false
  force-dns-mapping: true
  parse-pure-ip: true
dns:
  enable: true
  ipv6: false
  enhanced-mode: redir-host
  default-nameserver:
  - tls://223.5.5.5
  - tls://223.6.6.6
  nameserver:
  - https://dns.alidns.com/dns-query
  - https://doh.pub/dns-query
  fake-ip-filter:
  - rule-set:connectivity-check
  - rule-set:private_domain
  - rule-set:cn_domain
  - "+.miwifi.com"
  - "+.docker.io"
  - "+.market.xiaomi.com"
  - "+.push.apple.com"
  - beiyong.dynuddns.net
  - "*.lan"
  - localhost.ptlogin2.qq.com
  - "+.srv.nintendo.net"
  - "+.stun.playstation.net"
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - "+.xboxlive.com"
  - msftconnecttest.com
  - xbox.*.microsoft.com
  - "*.battlenet.com.cn"
  - "*.battlenet.com"
  - "*.blzstatic.cn"
  - "*.battle.net"
  - geosite:cn
  listen: 0.0.0.0:7874
proxy-groups:
- name: 一键连
  type: select
  proxies: *2
  include-all: true
  icon: https://github.com/666OS/YYDS/raw/main/mihomo/image/mihomo.png
- name: 故障转移
  type: fallback
  interval: 60
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: false
  proxies:
  - 香港自动
  - 台湾自动
  - 新加坡自动
  - 日本自动
  - 韩国自动
  - 美国自动
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/ULB.png
- name: AI平台
  type: select
  proxies: *3
  include-all: true
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/AI.png
- name: 国际媒体
  type: select
  proxies: *4
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/DomesticMedia.png
- name: 香港自动
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
  filter: "^(?=.*(?i)(港|\U0001F1ED\U0001F1F0|HK|Hong|HKG))(?!.*(排除1|排除2|5x)).*$"
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Hong_Kong.png
- name: 台湾自动
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
  filter: "^(?=.*(?i)(台|\U0001F1FC\U0001F1F8|\U0001F1F9\U0001F1FC|TW|tai|TPE|TSA|KHH))(?!.*(排除1|排除2|5x)).*$"
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Taiwan.png
- name: 新加坡自动
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
  filter: "^(?=.*(?i)(坡|\U0001F1F8\U0001F1EC|SG|Sing|SIN|XSP))(?!.*(排除1|排除2|5x)).*$"
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Singapore.png
- name: 日本自动
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
  filter: "^(?=.*(?i)(日|\U0001F1EF\U0001F1F5|JP|Japan|NRT|HND|KIX|CTS|FUK))(?!.*(排除1|排除2|5x)).*$"
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Japan.png
- name: 韩国自动
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
  filter: "^(?=.*(?i)(韩|\U0001F1F0\U0001F1F7|韓|首尔|南朝鲜|KR|KOR|Korea|South))(?!.*(排除1|排除2|5x)).*$"
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/Korea.png
- name: 美国自动
  type: url-test
  interval: 60
  tolerance: 20
  lazy: true
  url: https://www.gstatic.com/generate_204
  disable-udp: false
  timeout: 2000
  max-failed-times: 3
  hidden: true
  include-all: true
  filter: "^(?=.*(?i)(美|\U0001F1FA\U0001F1F8|US|USA|JFK|LAX|ORD|ATL|DFW|SFO|MIA|SEA|IAD))(?!.*(排除1|排除2|5x)).*$"
  icon: https://github.com/Koolson/Qure/raw/master/IconSet/Color/United_States.png
rule-providers:
  download:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/download.yaml
    path: "./rule_provider/download"
  fix-direct:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/fix-direct.yaml
    path: "./rule_provider/fix-direct"
  XPTV:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/XPTV.yaml
    path: "./rule_provider/XPTV"
  category-ai-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/category-ai-!cn.mrs
    path: "./rule_provider/category-ai-!cn"
  geolocation-!cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/geolocation-!cn.mrs
    path: "./rule_provider/geolocation-!cn"
  youtube:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/youtube.mrs
    path: "./rule_provider/youtube"
  spotify:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/spotify.mrs
    path: "./rule_provider/spotify"
  netflix:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/netflix.mrs
    path: "./rule_provider/netflix"
  disney:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/disney.mrs
    path: "./rule_provider/disney"
  hbo:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/hbo.mrs
    path: "./rule_provider/hbo"
  connectivity-check:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/connectivity-check.mrs
    path: "./rule_provider/connectivity-check"
  private_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/private.mrs
    path: "./rule_provider/private_domain"
  cn_domain:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/cn.mrs
    path: "./rule_provider/cn_domain"
  apple-cn:
    type: http
    interval: 86400
    behavior: domain
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/apple-cn.mrs
    path: "./rule_provider/apple-cn"
  cn_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/cn_ip.mrs
    path: "./rule_provider/cn_ip"
  private_ip:
    type: http
    interval: 86400
    behavior: ipcidr
    format: mrs
    url: https://github.com/666OS/YYDS/raw/main/mihomo/rules/private_ip.mrs
    path: "./rule_provider/private_ip"
  reject:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt
    path: "./rule_provider/reject"
  icloud:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt
    path: "./rule_provider/icloud"
  apple:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt
    path: "./rule_provider/apple"
  google:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt
    path: "./rule_provider/google"
  proxy:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt
    path: "./rule_provider/proxy"
  direct:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt
    path: "./rule_provider/direct"
  private:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt
    path: "./rule_provider/private"
  gfw:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt
    path: "./rule_provider/gfw"
  tld-not-cn:
    type: http
    interval: 86400
    behavior: domain
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt
    path: "./rule_provider/tld-not-cn"
  telegramcidr:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt
    path: "./rule_provider/telegramcidr"
  cncidr:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt
    path: "./rule_provider/cncidr"
  lancidr:
    type: http
    interval: 86400
    behavior: ipcidr
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt
    path: "./rule_provider/lancidr"
  applications:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://fastly.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt
    path: "./rule_provider/applications"
  openai:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/openai.yaml
    path: "./rule_provider/openai"
  bybit:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/bybit.yaml
    path: "./rule_provider/bybit"
  pikpak:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/pikpak.yaml
    path: "./rule_provider/pikpak"
  anthropic:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/anthropic.yaml
    path: "./rule_provider/anthropic"
  google-gemini:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/google-gemini.yaml
    path: "./rule_provider/google-gemini"
  xai:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/xai.yaml
    path: "./rule_provider/xai"
  perplexity:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/perplexity.yaml
    path: "./rule_provider/perplexity"
  microsoft:
    type: http
    interval: 86400
    behavior: classical
    format: yaml
    url: https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/microsoft.yaml
    path: "./rule_provider/microsoft"
  Rule-provider - cfg2aac5a:
    type: inline
    behavior: domain
    format: yaml
  Rule-provider - 代理:
    type: inline
    behavior: classical
    format: yaml
    payload:
    - DOMAIN,doi9.top
  Rule-provider - Direct:
    type: inline
    behavior: classical
    format: yaml
    payload:
    - DOMAIN-SUFFIX,oray.com
    - DOMAIN-KEYWORD,cloudflare
    - DOMAIN,owu.houu.de
rules:
- RULE-SET,Rule-provider - 代理,一键连
- RULE-SET,Rule-provider - Direct,DIRECT
- RULE-SET,Rule-provider - cfg2aac5a,DIRECT
- GEOIP,LAN,DIRECT,no-resolve
- GEOIP,CN,DIRECT,no-resolve
- RULE-SET,private_ip,DIRECT,no-resolve
- RULE-SET,cn_ip,DIRECT,no-resolve
- RULE-SET,download,DIRECT
- RULE-SET,cn_domain,DIRECT
- RULE-SET,apple-cn,DIRECT
- RULE-SET,fix-direct,DIRECT
- DST-PORT,123,DIRECT
- DOMAIN-SUFFIX,imee.me,DIRECT
- RULE-SET,category-ai-!cn,AI平台
- RULE-SET,youtube,国际媒体
- RULE-SET,spotify,国际媒体
- RULE-SET,netflix,国际媒体
- RULE-SET,disney,国际媒体
- RULE-SET,hbo,国际媒体
- RULE-SET,geolocation-!cn,一键连
- RULE-SET,XPTV,DIRECT
- RULE-SET,openai,AI平台
- RULE-SET,anthropic,AI平台
- RULE-SET,google-gemini,AI平台
- RULE-SET,xai,AI平台
- RULE-SET,perplexity,AI平台
- RULE-SET,applications,DIRECT
- RULE-SET,private,DIRECT
- RULE-SET,proxy,一键连
- RULE-SET,gfw,一键连
- RULE-SET,tld-not-cn,一键连
- RULE-SET,direct,DIRECT
- RULE-SET,lancidr,DIRECT,no-resolve
- RULE-SET,cncidr,DIRECT,no-resolve
- RULE-SET,telegramcidr,一键连,no-resolve
- MATCH,DIRECT
